# Generated by Django 2.2.7 on 2019-11-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
